print("Hello World")

f = open("hitesh.txt")
print(f.tell())
print(f.readline())
print(f.readline())
print(f.readline())
print(f.tell())
f.seek(0)
print(f.tell())
print(f.readline())
print(f.tell())
f.seek(78)
print(f.readline())
f.seek(0)
print(f.readline())
f.close()